version: '3.9'
name: production

services:
  seasonal_comment_face_survey:
    build: .
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:4567:4567"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    depends_on:
      - seasonal_comment_face_survey_migrate

  seasonal_comment_face_survey_migrate:
    build: .
    command: rake db:migrate
    env_file: .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
